- name: configuring mongodb server
  hosts: mongodb
  become: yes
  tasks:
   - name: copy mongodb repo file
     copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
   - name: install mongoodb server
     package:
        name: mongodb-org
        state: present
    
