[local]
localhost

[mongodb]
mongodb.daws90.fun

[redis]
redis.daws90.fun

[mysql]
mysql.daws90.fun

[rabbitmq]
rabbitmq.daws90.fun

[catalogue]
catalogue.daws90.fun


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb.daws90.fun
